### ISSUE TITLE
Unable to see sponsors on Firefox Version 61.0.1 (64-bit)

### ISSUE THREAD

**Issue by abs51295** [pyconau/2018.pycon-au.org#46]
I am unable to see gold sponsor(s) and Facebook while opening home page in Firefox. Also, on the Sponsors page I don't see logos for Google and Facebook.

<img width="1186" alt="screen shot 2018-07-18 at 11 28 06 pm" src="https://user-images.githubusercontent.com/13438222/42899043-8058c712-8ae2-11e8-835f-dc84e60d12ce.png">

**Comment by abs51295** [comment]
Did a force refresh but no luck. I am on Mac currently and the sponsor page looks like:
<img width="563" alt="screen shot 2018-07-19 at 10 44 16 am" src="https://user-images.githubusercontent.com/13438222/42922957-bfadf000-8b40-11e8-8c02-a33a95f7c115.png">

<img width="598" alt="screen shot 2018-07-19 at 10 44 26 am" src="https://user-images.githubusercontent.com/13438222/42922962-c5ad046e-8b40-11e8-9d14-9447ac63fac8.png">

**Comment by glasnt** [comment]
That's really strange. I'll look into it.

**Comment by abs51295** [comment]
Thanks @glasnt . Let me know if you need any help.

**Comment by katharosada** [comment]
I've tried on Firefox in a Mac,  and I don't see the issue either. Can you try disabling any adblocker or other extensions which might be interfering with the page?

Can you also check if these images load correctly for you individually:
https://2018.pycon-au.org/static/img/sponsors/facebook.png
https://2018.pycon-au.org/static/img/sponsors/google.png

And if possible, send as a copy of the html that you see when you view-source on the page so we can check that the image references are correctly there.

**Comment by abs51295** [comment]
Ad-blocker was the culprit 😄 . Closing the issue.

**Comment by glasnt** [comment]
That's.. interesting. Thanks for the diagnosis!
